### ISSUE TITLE
Cannot edit new text file in GCS Bucket

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#16]
It seems I am unable to edit text files inside a GCS bucket.

I tried both files created with elFinder and files uploaded directly in the Google Console.

Oddly, I can edit CSS files and I can even use the image resizer/cropper/rotator.

**Comment by matthewgoslett** [comment]
It sounds like this is an issue with elFinder?  I haven't looked too thoroughly but they don't appear to depend on our package.

**Comment by paulcanning** [comment]
I can edit files on a local file system, just not in GCS, so I'm sure its connected to your package?

**Comment by matthewgoslett** [comment]
How are you trying to edit the file(s)?
Can you paste me the sample code?

**Comment by paulcanning** [comment]
I am right clicking and selecting edit file. Code wise, I am using the most basic connector with a GCS adapter and the minimum code for the client.

```
public function elfinder_init()
	{
		$this->load->helper('path');
		$opts = array(
			'roots' => array(
				array(
					'driver' => 'LocalFileSystem',
					'path' => set_realpath('files'),
					'URL' => base_url('files') . '/'
				),
				array(
					'driver' => 'Flysystem',
					'alias' => 'GCS assets',
					'URL' => 'https://storage.googleapis.com/assets/',
					'filesystem' => new Filesystem($this->googleCloud('assets')),
					'separator' => '/',
					'defaults' => array('read' => true, 'write' => true)
				),
			)
		);
		$this->load->library('elfinder_lib', $opts);
	}
```

```
<script type="text/javascript" charset="utf-8">
			// Documentation for client options:
			// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
			$(document).ready(function() {
				$('#elfinder').elfinder({
					url : '<?php echo site_url('ex_cont/elfinder_init'); ?>'
				});
			});
		</script>
```

**Comment by cedricziel** [comment]
Yet you're still only showing thirdparty code.

**Comment by paulcanning** [comment]
Because that's all's I'm using...

**Comment by paulcanning** [comment]
OK, I got more information on this. Please see https://github.com/Studio-42/elFinder/issues/1300 for more info, as well as https://github.com/thephpleague/flysystem/issues/627

Basically, you cannot edit a new text file (empty file, 0b) in GCS, as the contents are returned as false, which gets passed through and matched as an error.

If the text file is empty, the content should be returned as such (`null` or `""`?)

Chap from Flysystem has pointed this towards you guys, so can you please investigate?

**Comment by paulcanning** [comment]
Any ideas?

**Comment by matthewgoslett** [comment]
I'm busy looking at this now

**Comment by matthewgoslett** [comment]
I'm able to replicate this, busy looking at a fix.
The GoogleClient $this->service->objects->get() call returns false when the object is empty (size 0).

**Comment by matthewgoslett** [comment]
Thanks for reporting this issue.
It's now fixed in https://github.com/Superbalist/flysystem-google-storage/releases/tag/1.0.3

**Comment by paulcanning** [comment]
Just downloaded 1.0.3 and it doesn't work. Still getting false for an empty text file.

**Comment by matthewgoslett** [comment]
I'm unable to replicate this using 1.0.3.

```
$result = $filesystem->put('blank.txt', '');
var_dump($result); // boolean true

$contents = $filesystem->read('blank.txt');
var_dump($contents); // null
```

**Comment by paulcanning** [comment]
Well I'm not sure what to tell you, but it is not working for me.

On line 260, `$contents` doesn't seem to be populated from `$this->service->objects->get($this->bucket, $path, ['alt' => 'media']);`

Putting a break point on that line, and stepping down to the next line (the IF statement), `$contents` is not present in my variables list in my IDE.
